### ISSUE TITLE
Shutter Is Not Capturing the Screenshot

### ISSUE THREAD

**Issue by programmer0073** [Pastafarianist/shutter#5]
I just Install Shutter Very Famous and Functionality Rich Screenshooting Utility On my Laptop Using Linux 17.10. I am Having a Problem While Capturing Screens. 

When I Capture Any Capture Full screen, Active Windows Screen, Or Selected Area Screen. It Takes This Kind Of Photos. While Capturing.
![Screenshot from 2017-12-18 15-46-01.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1513594084/xhfcgi0xatmxm1d8u6ts.png)
<center>Before Taking Screen Shots</center>
# Desktop Screen Capture:
Input

![Screenshot from 2017-12-18 15-46-14.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1513594201/krfys0ssickjvwvrpnd7.png)

![Workspace 1_011.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1513594340/xygsx4foh8nbguamxnaj.png)

# Active Window Capture:
Input:
![Screenshot from 2017-12-18 15-46-50.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1513594444/rascrimrgrmk85tutyoo.png)
Output:
![Screenshot from 2017-12-18 15-47-05.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1513594597/ahgj9609ikrh0h4sfw7e.png)

![Utopian - Rewarding Open Source Contributors - Google Chrome_013.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1513594670/l1gr4ddu6axeam1rwl8o.png)

Selected Area Capture:
![Screenshot from 2017-12-18 15-46-28.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1513594858/nfsgjghyqbnda1nnl5ev.png)

---

I Do not know that Why it is so.My system is Fully Updated and I installed Form the Offical Site. I want that It Should Be solved because It is a great tool for making tutorials ForSteemians :)

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@mohsan0073/shutter-is-not-capturing-the-screenshot">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by Pastafarianist** [comment]
Please see the discussion in https://github.com/Pastafarianist/shutter/issues/2.
