### ISSUE TITLE
Shutter crashes when choosing window from the list

### ISSUE THREAD

**Issue by sebma** [Pastafarianist/shutter#6]
Hi,

Both Shutter 0.90 and 0.93 crash on Ubuntu when trying to take a screen shot from the list of opened windows, here is the error message : 

```
Expecting 3181 bytes, got 53 at -1 at /usr/share/perl5/X11/Auth.pm line 39.
*** unhandled exception in callback:
***   Unexpected short read from authority file/tmp/kde-sebastien/xauth-1001-_0 at /usr/share/perl5/X11/Protocol.pm line 2303.
***  ignoring at /usr/bin/shutter line 2884.
```

Can you help me ?

**Comment by Pastafarianist** [comment]
Hi. This is not an official repository for Shutter, just a fork made to fix one bug. Please report all bugs to the [official bugtracker](https://bugs.launchpad.net/shutter).
